using Project_MyShop_2025.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Project_MyShop_2025.Core.Data
{
    public static class DbSeeder
    {
        public static void Seed(ShopDbContext context)
        {
            // Ensure database is created (optional, depends on migration strategy, but good for seeding)
            // context.Database.EnsureCreated(); // Don't do this if using Migrations

            if (context.Products.Any())
            {
                return; // DB has been seeded
            }

            // Categories should already be seeded by OnModelCreating if using HasData, 
            // but if we want to ensure they exist or add more:
            if (!context.Categories.Any())
            {
                var categories = new List<Category>
                {
                    new Category { Name = "Electronics", Description = "Devices and gadgets" },
                    new Category { Name = "Books", Description = "Readables and education" },
                    new Category { Name = "Clothing", Description = "Apparel and accessories" },
                    new Category { Name = "Photography", Description = "Cameras and lenses" }, // 4th category
                    new Category { Name = "Home & Garden", Description = "Furniture and tools" } // 5th category
                };
                context.Categories.AddRange(categories);
                context.SaveChanges();
            }

            // Products (22+)
            var products = new List<Product>();
            
            // Re-fetch categories to get valid IDs if they were autogenerated or if we want to match by name
            var electronics = context.Categories.FirstOrDefault(c => c.Name == "Electronics");
            var books = context.Categories.FirstOrDefault(c => c.Name == "Books");
            var clothing = context.Categories.FirstOrDefault(c => c.Name == "Clothing");
            var photography = context.Categories.FirstOrDefault(c => c.Name == "Photography");

            // We need IDs. If they are null (not found), we should probably handle it, but for seed we assume success.
            int elecId = electronics?.Id ?? 1;
            int bookId = books?.Id ?? 2;
            int clothId = clothing?.Id ?? 3;
            int photoId = photography?.Id ?? 1; // Fallback

            // Electronics (Laptop, Phone)
            products.Add(new Product { Name = "Gaming Laptop X1", Price = 15000000, ImportPrice = 12000000, Quantity = 10, CategoryId = elecId, Image = "Assets/Images/laptop.png", SKU = "ELEC001", Description = "High performance gaming laptop" });
            products.Add(new Product { Name = "Smartphone Pro Max", Price = 20000000, ImportPrice = 18000000, Quantity = 20, CategoryId = elecId, Image = "Assets/Images/phone.png", SKU = "ELEC002", Description = "Latest smartphone model" });
            products.Add(new Product { Name = "Wireless Earbuds", Price = 500000, ImportPrice = 300000, Quantity = 50, CategoryId = elecId, Image = "Assets/Images/laptop.png", SKU = "ELEC003", Description = "Noise cancelling earbuds" });
            products.Add(new Product { Name = "Gaming Mouse", Price = 300000, ImportPrice = 150000, Quantity = 100, CategoryId = elecId, Image = "Assets/Images/laptop.png", SKU = "ELEC004", Description = "RGB Gaming Mouse" });
            products.Add(new Product { Name = "Mechanical Keyboard", Price = 800000, ImportPrice = 600000, Quantity = 30, CategoryId = elecId, Image = "Assets/Images/laptop.png", SKU = "ELEC005", Description = "Blue switch keyboard" });
            products.Add(new Product { Name = "4K Monitor", Price = 5000000, ImportPrice = 4000000, Quantity = 15, CategoryId = elecId, Image = "Assets/Images/laptop.png", SKU = "ELEC006", Description = "27 inch 4K Monitor" });
            
            // Photography (Camera)
            products.Add(new Product { Name = "DSLR Camera", Price = 12000000, ImportPrice = 10000000, Quantity = 5, CategoryId = photoId, Image = "Assets/Images/camera.png", SKU = "CAM001", Description = "Professional DSLR" });
            products.Add(new Product { Name = "Tripod Stand", Price = 400000, ImportPrice = 250000, Quantity = 25, CategoryId = photoId, Image = "Assets/Images/camera.png", SKU = "CAM002", Description = "Aluminum tripod" });
            products.Add(new Product { Name = "Lens 50mm", Price = 2000000, ImportPrice = 1500000, Quantity = 8, CategoryId = photoId, Image = "Assets/Images/camera.png", SKU = "CAM003", Description = "Portrait lens" });

            // Clothing (Shirt)
            products.Add(new Product { Name = "Cotton T-Shirt", Price = 150000, ImportPrice = 80000, Quantity = 200, CategoryId = clothId, Image = "Assets/Images/phone.png", SKU = "CLOTH001", Description = "100% Cotton" }); // Reusing phone image as placeholder if needed, or I should have copied a 'shirt' one. I'll use phone or generic.
            products.Add(new Product { Name = "Jeans", Price = 400000, ImportPrice = 200000, Quantity = 100, CategoryId = clothId, Image = "Assets/Images/phone.png", SKU = "CLOTH002", Description = "Blue denim jeans" });
            products.Add(new Product { Name = "Jacket", Price = 600000, ImportPrice = 400000, Quantity = 50, CategoryId = clothId, Image = "Assets/Images/phone.png", SKU = "CLOTH003", Description = "Winter jacket" });
            products.Add(new Product { Name = "Running Shoes", Price = 900000, ImportPrice = 600000, Quantity = 40, CategoryId = clothId, Image = "Assets/Images/phone.png", SKU = "CLOTH004", Description = "Sports shoes" });

            // Books (No image? or generic) - I'll use laptop image as generic placeholder if needed, or null.
            // But let's reuse images 1, 2, 3 cyclically.
            products.Add(new Product { Name = "C# Programming", Price = 250000, ImportPrice = 150000, Quantity = 60, CategoryId = bookId, Image = "Assets/Images/laptop.png", SKU = "BOOK001", Description = "Learn C# globally" });
            products.Add(new Product { Name = "Clean Code", Price = 300000, ImportPrice = 200000, Quantity = 40, CategoryId = bookId, Image = "Assets/Images/laptop.png", SKU = "BOOK002", Description = "Robert C. Martin" });
            products.Add(new Product { Name = "The Pragmatic Programmer", Price = 350000, ImportPrice = 220000, Quantity = 35, CategoryId = bookId, Image = "Assets/Images/laptop.png", SKU = "BOOK003", Description = "Journey to mastery" });
            products.Add(new Product { Name = "Design Patterns", Price = 280000, ImportPrice = 180000, Quantity = 30, CategoryId = bookId, Image = "Assets/Images/laptop.png", SKU = "BOOK004", Description = "Gang of Four" });

            // More Electronics to fill up to 22+
            products.Add(new Product { Name = "Smart Watch", Price = 3000000, ImportPrice = 2500000, Quantity = 25, CategoryId = elecId, Image = "Assets/Images/phone.png", SKU = "ELEC007", Description = "Fitness tracker" });
            products.Add(new Product { Name = "Bluetooth Speaker", Price = 800000, ImportPrice = 500000, Quantity = 45, CategoryId = elecId, Image = "Assets/Images/phone.png", SKU = "ELEC008", Description = "Portable speaker" });
            products.Add(new Product { Name = "Power Bank", Price = 400000, ImportPrice = 250000, Quantity = 80, CategoryId = elecId, Image = "Assets/Images/phone.png", SKU = "ELEC009", Description = "10000mAh" });
            products.Add(new Product { Name = "USB C Cable", Price = 100000, ImportPrice = 50000, Quantity = 200, CategoryId = elecId, Image = "Assets/Images/phone.png", SKU = "ELEC010", Description = "Fast charging cable" });
            products.Add(new Product { Name = "HDMI Cable", Price = 120000, ImportPrice = 60000, Quantity = 150, CategoryId = elecId, Image = "Assets/Images/laptop.png", SKU = "ELEC011", Description = "4K Support" });
            
            // 6+3+4+4+5 = 22 products.
            products.Add(new Product { Name = "Webcam HD", Price = 700000, ImportPrice = 500000, Quantity = 25, CategoryId = elecId, Image = "Assets/Images/camera.png", SKU = "ELEC012", Description = "1080p Webcam" });

            context.Products.AddRange(products);
            context.SaveChanges();

            // Add some sample orders for dashboard testing
            if (!context.Orders.Any())
            {
                var random = new Random();
                var allProducts = context.Products.ToList();
                
                // Create 10 sample orders
                for (int i = 0; i < 10; i++)
                {
                    var order = new Order
                    {
                        CustomerName = $"Customer {i + 1}",
                        CustomerPhone = $"090{random.Next(1000000, 9999999)}",
                        CustomerAddress = $"Address {i + 1}",
                        CreatedAt = DateTime.Now.AddDays(-random.Next(0, 30)) // Random date within last 30 days
                    };

                    // Add 1-3 random items to each order
                    int itemCount = random.Next(1, 4);
                    var orderItems = new List<OrderItem>();
                    int orderTotal = 0;

                    for (int j = 0; j < itemCount; j++)
                    {
                        var product = allProducts[random.Next(allProducts.Count)];
                        int quantity = random.Next(1, 5);
                        int itemTotal = product.Price * quantity;
                        orderTotal += itemTotal;

                        orderItems.Add(new OrderItem
                        {
                            ProductId = product.Id,
                            Quantity = quantity,
                            Price = product.Price,
                            TotalPrice = itemTotal
                        });
                    }

                    order.TotalPrice = orderTotal;
                    order.Items = orderItems;
                    context.Orders.Add(order);
                }

                context.SaveChanges();
            }

            // Add some low-stock products for testing
            var lowStockProduct1 = context.Products.FirstOrDefault(p => p.SKU == "ELEC007");
            if (lowStockProduct1 != null) lowStockProduct1.Quantity = 3;
            
            var lowStockProduct2 = context.Products.FirstOrDefault(p => p.SKU == "BOOK003");
            if (lowStockProduct2 != null) lowStockProduct2.Quantity = 2;

            var lowStockProduct3 = context.Products.FirstOrDefault(p => p.SKU == "CAM001");
            if (lowStockProduct3 != null) lowStockProduct3.Quantity = 1;

            context.SaveChanges();
        }
    }
}
